#$var port = this.port || 5432;
#$ var start_command = this.start_command || 'node build/server.js';
services:
    ${name}:
        container_name: ${name}
        build:
            context: .
            dockerfile: ${MODULE_PATH + 'dockerfile'}
        working_dir: /usr/src/app
        volumes:
            - ${server_code_dir}:/usr/src/app/build
        command: ${start_command}

        expose:
            - ${port}
        env_file:
            ${env}
        #environment:
            #VIRTUAL_HOST: "myamazingdomain.com"
            #VIRTUAL_PORT: 3000
            #NODE_ENV: "production"

        #$ var databases = Object.keys(other).filter(moduleName => other[moduleName].isDB);
        #$if (databases.length > 0) {
        depends_on:
            #$for (var db of databases) {
            - ${other[db].name}
            #$}}