services:
    ${fullName}:
        container_name: ${fullName}
        build:
            context: ${moduleDir}
            dockerfile: dockerfile
        working_dir: /usr/src/app
        volumes:
            - ${server_code_dir}:/usr/src/app/build
        #$ var start_command = this.start_command || 'node build/server.js';
        command: ${start_command}

        #$if (this.ports && ports.length > 0)
        expose:
            #$for (var port of ports)
            - ${port}
            #$

        env_file:
            ${env.file}
        #environment:
            #VIRTUAL_HOST: "myamazingdomain.com"
            #VIRTUAL_PORT: 3000
            #NODE_ENV: "production"

        #$ var databases = Object.keys(other).filter(moduleName => other[moduleName].isDB);
        #$if (databases.length > 0)
        depends_on:
            #$for (var db of databases)
            - ${other[db].fullName}
            #$