services:
    ${name}:
        container_name: ${name}
        build:
            context: .
            dockerfile: ${MODULE_PATH + 'dockerfile'}
        working_dir: /usr/src/app
        volumes:
            - ${server_code}:/usr/src/app/build
        command: ${start_command}
        expose:
            - ${port}
        env_file:
            ${env}
        #environment:
            #VIRTUAL_HOST: "myamazingdomain.com"
            #VIRTUAL_PORT: 3000
            #NODE_ENV: "production"
        depends_on:
            - my-postgres-db
        depends_on:
            #$for (item of dependencies) {
            - ${item}
            #$}