services:
    ${name}:
        # https://hub.docker.com/r/jwilder/nginx-proxy
        container_name: ${name}
        image: jwilder/nginx-proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${certs_dir}:/etc/nginx/certs
            - ${vhost_dir}:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro

            # volume для статического контента,
            # путь(то, что правее двоеточия) взят с потолка, он может быть любым другим
            # только продублируй его в файле proxy/vhost.d/default_location
            #- ./web_static:/var/www/html
            #- ./proxy/html:/usr/share/nginx/html
            - ${static_dir}:/usr/share/nginx/html