services:
    your-postgres:
        container_name: your-postgres
        image: postgres:12.3-alpine
        env_file: _your-postgres.env
        volumes:
            - ./postgres_data/:/var/lib/postgresql/data:rw
        expose:
            - 5432
    your-couch:
        container_name: your-couch
        image: couchdb:3.1.1
        env_file: _your-couch.env
    your-nginx-proxy:
        container_name: your-nginx-proxy
        image: jwilder/nginx-proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - _certs:/etc/nginx/certs
            - _vhost:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
    your-nodejs:
        container_name: your-nodejs
        build:
            context: deep/path/nodejs/
            dockerfile: dockerfile
        working_dir: /usr/src/app
        volumes:
            - nodejsCode:/usr/src/app/build
        command: node build/server.js
        expose:
            - 5432
        env_file: _your-nodejs.env
        depends_on:
            - your-postgres
            - your-couch
