services:
    ${name}:
        container_name: ${name}
        image: postgres:12.3-alpine
        env_file:
            _postgres.env
        volumes:
            - ${data_dir}:/var/lib/postgresql/data:rw
            - ${init_dir}:/docker-entrypoint-initdb.d
        expose:
            - ${db_port}